version: '3.8'

services:
  postgres:
    image: postgres:15
    profiles: [ "local-db" ]
    environment:
      POSTGRES_DB: vaultmanager
      POSTGRES_USER: vaultmgr
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vault-net
    restart: always

  backend:
    image: ${DOCKER_USERNAME}/vault-backend:latest
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://vaultmgr:changeme@postgres:5432/vaultmanager}
      SECRET_KEY: ${SECRET_KEY:-changeme}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY:-ZE0lriVLEvwGa7iXvR7asxBr2yzf6Kf-5VN1409ywj0=}
    networks:
      - vault-net
    restart: always

  frontend:
    image: ${DOCKER_USERNAME}/vault-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - vault-net
    restart: always

volumes:
  postgres_data:


networks:
  vault-net:
