"""change_auto_unseal_enabled_to_boolean

Revision ID: 4ee30955056c
Revises: e1dfb098bf55
Create Date: 2026-02-07 22:30:52.844539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ee30955056c'
down_revision: Union[str, None] = 'e1dfb098bf55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Convert auto_unseal_enabled from INTEGER to BOOLEAN
    op.execute("""
        ALTER TABLE vaults 
        ALTER COLUMN auto_unseal_enabled TYPE BOOLEAN 
        USING CASE WHEN auto_unseal_enabled = 0 THEN FALSE ELSE TRUE END
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
