"""add_last_auto_unseal_check

Revision ID: 69314a0ffbea
Revises: 4ee30955056c
Create Date: 2026-02-07 22:36:08.737444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69314a0ffbea'
down_revision: Union[str, None] = '4ee30955056c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaults', sa.Column('last_auto_unseal_check', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vaults', 'last_auto_unseal_check')
    # ### end Alembic commands ###
