"""Initial migration

Revision ID: cb4b68cf36d6
Revises: e75263939a9e
Create Date: 2026-02-07 21:29:27.447201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb4b68cf36d6'
down_revision: Union[str, None] = 'e75263939a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('auth_method', sa.String(), nullable=True),
    sa.Column('encrypted_token', sa.String(), nullable=True),
    sa.Column('role_id', sa.String(), nullable=True),
    sa.Column('encrypted_secret_id', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaults_id'), 'vaults', ['id'], unique=False)
    op.create_index(op.f('ix_vaults_name'), 'vaults', ['name'], unique=True)
    op.create_table('vault_unseal_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vault_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_key', sa.String(), nullable=False),
    sa.Column('key_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vault_unseal_keys_id'), 'vault_unseal_keys', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vault_unseal_keys_id'), table_name='vault_unseal_keys')
    op.drop_table('vault_unseal_keys')
    op.drop_index(op.f('ix_vaults_name'), table_name='vaults')
    op.drop_index(op.f('ix_vaults_id'), table_name='vaults')
    op.drop_table('vaults')
    # ### end Alembic commands ###
