"""Add auto-unseal fields

Revision ID: e1dfb098bf55
Revises: cb4b68cf36d6
Create Date: 2026-02-07 21:49:01.686148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1dfb098bf55'
down_revision: Union[str, None] = 'cb4b68cf36d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaults', sa.Column('auto_unseal_enabled', sa.Integer(), nullable=True))
    op.add_column('vaults', sa.Column('auto_unseal_interval_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vaults', 'auto_unseal_interval_minutes')
    op.drop_column('vaults', 'auto_unseal_enabled')
    # ### end Alembic commands ###
